name: conexion 

on:
    push:
      branches:
        - main

jobs:
    container-job:
        
        runs-on: ubuntu-latest
        
        container: node:10.18-jessie
    
        
        services:
          
          postgres:
            
            image: postgres
            
            env:
              POSTGRES_PASSWORD: 060911River.
            
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    
        steps:
          
          - name: Check out repository code
            uses: actions/checkout@v4
    
          
          - name: Install dependencies
            run: npm ci
    
          - name: Connect to PostgreSQL
            
            run: node index.js
            
            env:
              
              POSTGRES_HOST: localhost
             
              POSTGRES_PORT: 5432